language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install coveralls pep8 pep257 restructuredtext_lint
  - python setup.py install
script:
  - python setup.py test
  - pep8 --ignore=E501 resync-simulator simulator
  - pep257 resync-simulator simulator
  - rst-lint README
  - coverage run --source=simulator setup.py test
after_success:
  - coveralls
