language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
# need "python setup.py install" to install resync so that client tests work
install:
  - pip install resync tornado pyyaml
  - pip install coveralls pep257 restructuredtext_lint testfixtures
  - python setup.py install
# command to run tests
script:
  - python setup.py test
#  - pep257 simulator
  - rst-lint README
  - coverage run --source=resync setup.py test
after_success:
  - coveralls