# The default ResourceSync simulator configuration

##### Source Configuration #####

source:
    name: ResourceSync Simulator
    number_of_resources: 1000
    change_frequency: 0.5
    event_types: [create, update, delete]
    average_payload: 1000
    max_events: -1

##### Inventory Configuration #####

# The Source exposes a dynamic inventory
inventory:
    class: DynamicSourceInventory
    uri_path: sitemap.xml

# The Source exposes a static inventory
# inventory:
#     class: StaticSourceInventory
#     interval: 30
#     uri_path: sitemap.xml

##### ChangeMemory Configuration #####

# Change memory implementation used in the simulation
changememory:
    class: DynamicChangeSet
    uri_path: changes

##### Publisher Configuration #####

# Event logger settings
logger:
    class: ConsoleEventLog
