# The default ResourceSync simulator configuration

# Source parameter settings
source:
    name: Default Simulator Settings
    number_of_resources: 100
    change_frequency: 1
    event_types: [create, update, delete]
    average_payload: 1000
    max_events: -1

# The inventory view to be applied on this source
inventory:
    class: DynamicSiteMapInventory
    url: /sitemap.xml
    
# The publisher implementation to send notifications
publisher:
    class: SimplePublisher


# Event logger settings
logger:
    class: ConsoleEventLog
