# Default ResourceSync simulator configuration

# Source parameter settings
source:
    name: Sample Simulator Settings
    number_of_resources: 1000
    change_frequency: 0.5
    event_types: [create, update, delete]
    average_payload: 1000
    max_events: -1

# Change memory implementation used in the simulation
changememory:
    class: DynamicChangeSet
    uri_path: /changes

# Event logger settings
logger:
    class: ConsoleEventLog
