# The default ResourceSync simulator configuration

# Source parameter settings
source:
    number_of_resources: 100
    change_frequency: 1
    event_types: [create, update, delete]
    average_payload: 1000
    max_events: -1

# The inventory view to be applied on the repository
inventory:
    name: DynamicSiteMap