# The default ResourceSync simulator configuration

##### Source Configuration #####

source:
    name: ResourceSync Simulator
    number_of_resources: 1000
    change_delay: 2
    event_types: [create, update, delete]
    average_payload: 1000
    max_events: -1
    stats_interval: 10

##### Resource List Builder Implementations #####

# A dynamic builder that creates inventories at request time
resource_list_builder:
    class: DynamicResourceListBuilder
    uri_path: resourcelist.xml

##### ChangeMemory Implementations #####

# A dynamic memory-based change memory
changememory:
    class: DynamicChangeList
    uri_path: changelist.xml
    max_changes: 1000