# The default ResourceSync simulator configuration

##### Source Configuration #####

source:
    name: ResourceSync Simulator
    number_of_resources: 1000
    change_delay: 2
    event_types: [create, update, delete]
    average_payload: 1000
    max_events: -1
    stats_interval: 10

##### ResourceList Builder Implementations #####

# A dynamic builder that creates inventories at request time
# resourcelist_builder:
#     class: DynamicResourceListBuilder
#     uri_path: sitemap.xml

# A static builder that creates and writes inventories in given intervals
resourcelist_builder:
    class: StaticResourceListBuilder
    max_sitemap_entries: 500
    interval: 30
    uri_path: sitemap.xml

##### ChangeMemory Implementations #####

# A dynamic memory-based change memory
# changememory:
#     class: DynamicChangeList
#     uri_path: changelist
#     max_changes: 1000

# A static file-based change memory
changememory:
    class: StaticChangeList
    uri_path: changelists
    uri_file: most_recent.xml
    max_sitemap_entries: 50
    max_changes: 50

##### Publisher implementations #####

# publisher:
#     class: XMPPPublisher
#     jid: publisher_jid
#     pwd: pwd
#     pubsub_node: node_name
#     pubsub_jid: pubsub.host